server:
  port: 9090
spring:
  application:
    name: Political-party-service
  zipkin:
    base-url: http://localhost:9411/zipkin/
  datasource:
    url: jdbc:mysql://localhost:3306/politicalparty
    username: politicalparty
    password: politicalparty
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    